Added TODOs.

diff --git a/src/etc/init.d/gpgmailer b/src/etc/init.d/gpgmailer
--- a/src/etc/init.d/gpgmailer
+++ b/src/etc/init.d/gpgmailer
@@ -41,24 +41,26 @@ SCRIPTNAME=/etc/init.d/$NAME
 #
 do_start()
 {
-	# Yeah, we should probably do this in gpgmailer.py but we need to get this done.
-    # This does not honor the config and should be fixed.
+    # Yeah, we should probably do this in gpgmailer.py but we need to get this done.
+    # TODO: This does not honor the config and should be fixed. Probably best to move
+    #   this into gpgmailer-daemon.py
 
-	# Create /tmp if it doesn't exist (it should exist)	
-	if [ ! -d "/tmp/gpgmailer" ]; then
-		mkdir -p /tmp/gpgmailer
-	fi
-	# If /tmp/gpgmailer is empty and not mounted as a ramdisk, mount it as a ramdisk.
-	# TODO: Replace 'ls' with 'find'
-	if [ ! "$(ls -A /tmp/gpgmailer/ 2> /dev/null)" ] && [ ! "$(mount | grep '^none on /tmp/gpgmailer type tmpfs ')" ]; then
-		cd /tmp
-		mount -t tmpfs -o size=25% none gpgmailer 
-	fi
-	# If /tmp/gpgmailer is not mounted as a ramdisk, something is wrong. Bail!
-	if [ ! "$(mount | grep '^none on /tmp/gpgmailer type tmpfs ')" ]; then
-		echo 'Count not mount /mnt/gpgmailer as a ramdisk. Startup failed.'
-		return 2
-	fi
+    # Create /tmp if it doesn't exist (it should exist)    
+    if [ ! -d "/tmp/gpgmailer" ]; then
+        mkdir -p /tmp/gpgmailer
+    fi
+    # If /tmp/gpgmailer is empty and not mounted as a ramdisk, mount it as a ramdisk.
+    # TODO: Replace 'ls' with 'find'
+    # TODO: Put through shellcheck.
+    if [ ! "$(ls -A /tmp/gpgmailer/ 2> /dev/null)" ] && [ ! "$(mount | grep '^none on /tmp/gpgmailer type tmpfs ')" ]; then
+        cd /tmp
+        mount -t tmpfs -o size=25% none gpgmailer 
+    fi
+    # If /tmp/gpgmailer is not mounted as a ramdisk, something is wrong. Bail!
+    if [ ! "$(mount | grep '^none on /tmp/gpgmailer type tmpfs ')" ]; then
+        echo 'Count not mount /mnt/gpgmailer as a ramdisk. Startup failed.'
+        return 2
+    fi
     if [ ! -d "/tmp/gpgmailer/outbox" ]; then
         mkdir "/tmp/gpgmailer/outbox"
     fi
@@ -69,16 +71,16 @@ do_start()
         [ ! -d "/tmp/gpgmailer/draft" ]; then
         echo 'Count not create required sub directories in /tmp/gpgmailer/.'
     fi
-	
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --name python2 --startas $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --name python2 --startas $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
+    
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --name python2 --startas $DAEMON --test > /dev/null \
+        || return 1
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --name python2 --startas $DAEMON -- \
+        $DAEMON_ARGS \
+        || return 2
 }
 
 #
@@ -86,71 +88,71 @@ do_start()
 #
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name python2
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	if [ "$(mount | grep '^none on /tmp/gpgmailer type tmpfs (rw,size=25%)$')" ]; then
-	    umount "/tmp/gpgmailer"
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name python2
+    RETVAL="$?"
+    [ "$RETVAL" = 2 ] && return 2
+    # Many daemons don't delete their pidfiles when they exit.
+    rm -f $PIDFILE
+    if [ "$(mount | grep '^none on /tmp/gpgmailer type tmpfs (rw,size=25%)$')" ]; then
+        umount "/tmp/gpgmailer"
     fi
-	if [ "$(mount | grep '^none on /tmp/gpgmailer type tmpfs (rw,size=25%)$')" ]; then
+    if [ "$(mount | grep '^none on /tmp/gpgmailer type tmpfs (rw,size=25%)$')" ]; then
         echo "Failed to umount /tmp/gpgmailer"
     else
         if [ -d "/tmp/gpgmailer" ]; then
             rmdir "/tmp/gpgmailer"
         fi
     fi
-	return "$RETVAL"
+    return "$RETVAL"
 }
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    do_stop
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   status)
-	status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
-	;;
+    status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
+    ;;
   restart|force-reload)
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-		# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+            0) log_end_msg 0 ;;
+            1) log_end_msg 1 ;; # Old process is still running
+            *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+        ;;
+    esac
+    ;;
   *)
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-	exit 3
-	;;
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    exit 3
+    ;;
 esac
 
 :
